---
title: Derivatives of vector functions
---

\renewcommand{\vec}[1]{\mathbf{#1}}
\newcommand{\v}[1]{\left\langle #1\right\rangle}
\newcommand{\norm}[1]{\left\lvert#1 \right\rvert}

```{r, echo=FALSE}
webwork <- function(path, width, height)
{
    htmltools::tags$iframe(title = "Exercise", 
                           src=paste0("https://webwork.svsu.edu/webwork2/html2xml?
&answersSubmitted=0
&sourceFilePath=", path, "&problemSeed=123
&displayMode=MathJax
&courseID=daemon_course
&userID=daemon
&course_password=daemon
&outputformat=simple"), width=width, height=height, frameborder="0")
}

illustr <- function(fname, title, width, height)
{
    copied <- file.copy(fname, ".", overwrite = TRUE)
    htmltools::tags$iframe(title = title, src = basename(fname), width=width, height=height, frameborder="0")
}
```

## Derivatives and tangent vectors

A derivative of a vector function $\vec{r}:\mathbb{R} \to \mathbb{R}^n$ is
defined as

$$\vec{r}'(t) = \lim_{h\to 0}\frac{\vec{r}(t+h) - \vec{r}(t)}{h}$$

The resulting _vector_ is _tangent_ to the curve:

```{r, echo=FALSE}
illustr("../../asymptote/vector_functions/tangent.html", title = "Tangent vector to a curve", width=600, height=400)
```

There are more details in the following video:

```{r echo=FALSE}
vembedr::embed_youtube("iAKfjNwCJmc")
```

### Try it yourself

```{r, echo=FALSE}
webwork(
        "Library/Dartmouth/setStewartCh14S2/problem_1.pg",
        width=640, height=500
)
```

```{r, echo=FALSE}
webwork(
        "Library/BentleyUniversity/MathematicsOfComputerGraphics/setMoCG-Ch10/10-1-to-3-VectorValuedPolynomialsAndLogs.pg",
        width=640, height=500
)
```
