---
title: Substitution for Multiple Integrals
format: html
layout: article
reference-location: margin
knitr:
  opts_chunk: 
    echo: false
---

{{< include ../../_common.qmd >}}

## Substitution (change of variable) in multiple integrals

### Explanation and derivation:

```{r}
vembedr::embed_youtube("KlNcZcI4wpc")
```

### Summary, Jacobians

```{r}
vembedr::embed_youtube("CTsRERGu_H4")
```

#### Try it yourself

```{r}
webwork(
        "Library/Michigan/Chap16Sec7/Q01.pg",
        width=640, height=500
)
```

```{r}
webwork(
        "Library/Hope/Multi2/11-04-MV-Int-change-var/Change-variables-01.pg",
        width=640, height=500
)
```

```{r}
webwork(
        "Library/WHFreeman/Rogawski_Calculus_Early_Transcendentals_Second_Edition/15_Multiple_Integration/15.6_Change_of_Variables/15.6.23.pg",
        width=640, height=500
)
```

```{r}
webwork(
        "Library/Michigan/Chap16Sec7/Q05.pg",
        width=640, height=500
)
```

### Examples

#### Polar coordinate transformation

```{r}
vembedr::embed_youtube("3nTbXYz6HWA")
```

#### Another example of substitution in 2 variables

```{r}
vembedr::embed_youtube("lNi6s0b6HKc")
```

#### An example of substitution in 3 variables (spherical coordinate transformation)

```{r}
vembedr::embed_youtube("rOsUNGU2H9s")
```

#### Try it yourself

```{r}
webwork(
        "Library/Michigan/Chap16Sec7/Q19.pg",
        width=640, height=500
)
```

```{r}
webwork(
        "Library/WHFreeman/Rogawski_Calculus_Early_Transcendentals_Second_Edition/15_Multiple_Integration/15.6_Change_of_Variables/15.6.33.pg",
        width=640, height=500
)
```

```{r}
webwork(
        "Library/Michigan/Chap16Sec7/Q25.pg",
        width=640, height=500
)
```
