---
title: Dot Product continued
format: html
layout: article
reference-location: margin
knitr:
  opts_chunk: 
    echo: false
---

{{< include ../_common.qmd >}}

## Projections

One of the main applications of dot product is in calculating a projection of
one vector onto another

```{r echo=FALSE}
vembedr::embed_youtube("WMUvFjfHUHw")
```

The two important formulas are:

$$\begin{aligned}
\operatorname{comp}_{\vec{b}}\vec{a} &= \frac{\vec{a}\cdot\vec{b}}{\norm{\vec{b}}}\\
\operatorname{proj}_{\vec{b}}\vec{a} &= \frac{\vec{a}\cdot\vec{b}}{\vec{b}\cdot\vec{b}}\vec{b}
\end{aligned}$$


### Try it yourself

```{r, echo=FALSE}
webwork(
        "Library/272/setStewart12_3/problem_4.pg",
        width=800, height=500
)
```

```{r, echo=FALSE}
webwork(
        "Library/NAU/setCalcII/vector_projections.pg",
        width=800, height=500
)
```

## Direction cosines

One way to describe the _direction_ of a vector $\vec{v}$ in 3d is by giving a unit
vector with the same direction as $\vec{v}$.  What is the actual meaning of its
components?

```{r echo=FALSE}
vembedr::embed_youtube("v3Eyi5jINlE")
```

### Try it yourself

```{r, echo=FALSE}
webwork(
        "Library/BentleyUniversity/MathematicsOfComputerGraphics/setMoCG-Ch4/4-4-MagnitudeAndDirectionDecimals3D.pg",
        width=640, height=500
)
```

```{r, echo=FALSE}
webwork(
        "Library/BentleyUniversity/MathematicsOfComputerGraphics/setMoCG-Ch4/4-4-MagnitudeAndDirectionFormulas3D.pg",
        width=640, height=500
)
```

